version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: notlim254/node_live_app
    ports:
      - "3004:3004"
    depends_on:
      - node_db
    environment:
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - .:/usr/src/app

  node_db:
    container_name: node_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
