version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: notlim254/node_live_app
    ports:
      - "3004:3004"
    depends_on:
      - node_db
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=node_db
      - DB_PORT=5432
      - DB_DATABASE=greenvoyage
      - DB_USERNAME=postgres
      - DB_PASSWORD=Password
    restart: always
    networks:
      - app-network
      
  node_db:
    container_name: node_db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
      - POSTGRES_DB=greenvoyage
    ports:
      - "5432:5432"
    volumes:
      - node_db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  node_db_data: {}

networks:
  app-network:
