version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: notlim254/node_live_app
    ports:
      - "3004:3004"
    depends_on:
      - node_db
    environment:
      - PG_DB=greenvoyage
      - PG_USER=postgres
      - PG_PASSWORD=Password
      - PG_HOST=node_db
    restart: always
    networks:
      - app-network
      
  node_db:
    container_name: node_db
    image: postgres:13
    environment:
      - POSTGRES_DB=greenvoyage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
    ports:
      - "5432:5432"
    volumes:
      - node_db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  node_db_data: {}

networks:
  app-network:
